server:
  port: '8080'
  servlet:
    context-path: /demo

logging:
  file: 
    max-size:
    max-history: 
    path: 
    name: 
    
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  freemarker:
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: com.saltlux.assembly.common.SQLDialect
  datasource:
    url: jdbc:sqlite:demo.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
    hikari:
      maximum-pool-size: '10'
  devtools:
    livereload:
      enabled: 'true'

mybatis:
  type-aliases-package: com.saltlux.assembly
  mapper-locations: /mapper/**/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: 'true'
    call-setters-on-nulls: 'true'
